<script setup lang="ts">
import { ElConfigProvider } from 'element-plus'
import UrlLink from './UrlLink.vue'
import PasswordDialog from './PasswordDialog.vue'
import Backups from './Backups.vue'
import { certificateLabel } from './certificate'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import { computed, onMounted, onUnmounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { api, beijingTime, setCSRF, siteInput, stateLabel, type Incident, type Overview, type Page, type Session, type Site } from './api'
const route = useRoute(), router = useRouter()
const session = ref<Session | null>(null), ready = ref(false), error = ref(''), busy = ref(false), feedback = ref('')
const login = reactive({ username: 'admin', password: '' })
const overview = ref<Overview>({ total: 0, normal: 0, down: 0, pending: 0, paused: 0, scheduler_healthy: true })
const sites = ref<Site[]>([]), incidents = ref<Incident[]>([]), detail = ref<Site | null>(null), total = ref(0), historyTotal = ref(0)
const filter = reactive({ q: '', node: '', status: '', page: 1, page_size: 20 }), historyPage = ref(1)
const passwordDialog = ref(false)
const dialog = ref(false), editId = ref(0), deleteId = ref(0)
const form = reactive({ name: '', url: '', node: '', keyword: '', slow_alert: false, paused: false })
const section = computed(() => route.path.startsWith('/websites/') ? 'detail' : route.path === '/websites' ? 'websites' : route.path === '/incidents' ? 'incidents' : route.path === '/backups' ? 'backups' : 'overview')
const title = computed(() => ({ overview: '监控概览', websites: '网站管理', detail: '网站详情', incidents: '故障历史', backups: '备份管理' }[section.value]))
let timer: ReturnType<typeof setInterval> | undefined, loading = false, generation = 0
function fail(e: unknown) { error.value = e instanceof Error ? e.message : '操作失败，请稍后重试' }
async function auth() { try { session.value = await api<Session>('/api/session'); setCSRF(session.value.csrf_token); if (route.path === '/login') await router.replace('/') } catch { session.value = null; await router.replace('/login') } finally { ready.value = true } }
async function signIn() { busy.value = true; error.value = ''; try { session.value = await api<Session>('/api/login', 'POST', login); setCSRF(session.value.csrf_token); login.password = ''; await router.replace('/'); await refresh() } catch (e) { fail(e) } finally { busy.value = false } }
async function signOut() { try { await api('/api/logout', 'POST'); session.value = null; setCSRF(''); await router.replace('/login') } catch (e) { fail(e) } }
async function refresh() {
 if (!session.value || document.hidden || loading) return
 loading = true; const current = generation, requestedSection = section.value
 try {
  if (requestedSection === 'overview') { const [counts, history] = await Promise.all([api<Overview>('/api/overview'), api<Page<Incident>>('/api/incidents?page=1&page_size=20')]); if (current === generation) { overview.value = counts; incidents.value = history.items } }
  else if (requestedSection === 'websites') { const data = await api<Page<Site>>('/api/websites?' + new URLSearchParams(Object.entries(filter).map(([k, v]) => [k, String(v)]))); if (current === generation) { sites.value = data.items; total.value = data.total } }
  else if (requestedSection !== 'backups') { const id = requestedSection === 'detail' ? Number(route.params.id) : 0; const [site, history] = await Promise.all([id ? api<Site>(`/api/websites/${id}`) : Promise.resolve(null), api<Page<Incident>>(`${id ? `/api/websites/${id}` : '/api'}/incidents?page=${historyPage.value}&page_size=20`)]); if (current === generation) { detail.value = site; incidents.value = history.items; historyTotal.value = history.total } }
 } catch (e) { fail(e) } finally { loading = false; if (current !== generation) void refresh() }
}
function openForm(site?: Site) { error.value = ''; editId.value = site?.id || 0; Object.assign(form, site ? siteInput(site) : { name: '', url: '', node: '', keyword: '', slow_alert: false, paused: false }); dialog.value = true }
async function save() { busy.value = true; error.value = ''; try { await api(`/api/websites${editId.value ? '/' + editId.value : ''}`, editId.value ? 'PUT' : 'POST', form); dialog.value = false; feedback.value = '网站设置已保存，检测无需重启容器'; await refresh() } catch (e) { fail(e) } finally { busy.value = false } }
async function toggle(site: Site) { error.value = ''; try { await api(`/api/websites/${site.id}`, 'PUT', { ...siteInput(site), paused: !site.paused }); feedback.value = site.paused ? '已恢复网站检测' : '已暂停网站检测'; await refresh() } catch (e) { fail(e) } }
async function remove() { busy.value = true; try { await api(`/api/websites/${deleteId.value}`, 'DELETE'); deleteId.value = 0; feedback.value = '网站已删除，已有故障历史仍保留'; if (section.value === 'detail') await router.push('/websites'); await refresh() } catch (e) { fail(e) } finally { busy.value = false } }
async function check(site: Site) { try { await api(`/api/websites/${site.id}/check`, 'POST'); feedback.value = '已加入检查队列，结果会自动刷新' } catch (e) { fail(e) } }
function search() { filter.page = 1; generation++; void refresh() }
function nodeName(id: string) { return session.value?.nodes.find(n => n.id === id)?.name || '未关联' }
function kindName(kind: string) { return ({ outage: '访问故障', slow: '响应缓慢', certificate: '证书即将到期' }[kind] || kind) }
async function passwordChanged() { session.value = null; setCSRF(''); await router.replace('/login'); error.value = '密码已修改，请使用新密码重新登录' }
function expired() { session.value = null; setCSRF(''); void router.replace('/login'); error.value = '登录已失效，请重新登录' }
function visibility() { if (!document.hidden) void refresh() }
watch(() => route.fullPath, () => { generation++; historyPage.value = 1; error.value = ''; feedback.value = ''; void refresh() })
onMounted(async () => { await auth(); await refresh(); timer = setInterval(() => void refresh(), 15000); document.addEventListener('visibilitychange', visibility); window.addEventListener('session-expired', expired) })
onUnmounted(() => { clearInterval(timer); document.removeEventListener('visibilitychange', visibility); window.removeEventListener('session-expired', expired) })
</script>

<template>
 <el-config-provider :locale="zhCn">
 <div v-if="!ready" class="boot">正在连接网站监控后台…</div>
 <main v-else-if="!session" class="login-screen">
  <div class="login-intro"><span class="wordmark">DZH · WEBSCAN</span><h1>让每一个网站<br>都在你的掌握之中。</h1><p>首页可用性 · 证书到期 · 故障恢复</p><div class="intro-note">由主服务器持续检查，异常及时送达飞书。</div></div>
  <el-card class="login-card" shadow="never"><span class="eyebrow">网站监控管理</span><h2>登录管理后台</h2><p class="muted">使用安装账号；修改密码后请使用最新密码。</p><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-form label-position="top" @submit.prevent="signIn"><el-form-item label="管理员账号"><el-input v-model="login.username" autocomplete="username" placeholder="请输入账号" /></el-form-item><el-form-item label="密码"><el-input v-model="login.password" type="password" show-password autocomplete="current-password" placeholder="请输入密码" /></el-form-item><el-button type="primary" native-type="submit" :loading="busy" class="full">登录</el-button></el-form><p class="small muted">检测结果代表主服务器对网站的访问情况。</p></el-card>
 </main>
 <div v-else class="shell">
  <aside><div class="brand"><span class="brand-icon">W</span><div>智慧网站监控<small>DZH WEBSCAN</small></div></div><span class="nav-caption">管理工作台</span><nav><router-link to="/" :class="{ active: section === 'overview' }">◈ &nbsp; 监控概览</router-link><router-link to="/websites" :class="{ active: section === 'websites' || section === 'detail' }">▤ &nbsp; 网站管理</router-link><router-link to="/incidents" :class="{ active: section === 'incidents' }">◷ &nbsp; 故障历史</router-link><router-link to="/backups" :class="{ active: section === 'backups' }">▣ &nbsp; 备份管理</router-link></nav><div class="sidebar-foot"><span class="online-dot"></span> 主服务器统一检测<br><small>后台每 15 秒自动刷新</small></div></aside>
  <div class="workspace"><header><span>网站可用性 / {{ title }}</span><div>{{ session.username }} <el-button text @click="passwordDialog = true">修改密码</el-button><el-button text @click="signOut">退出登录</el-button></div></header><main class="content">
   <div class="page-heading"><div><span class="eyebrow">WEBSITE MONITOR</span><h1>{{ title }}</h1><p class="muted">及时发现访问故障，保留每一次异常与恢复。</p></div><el-button v-if="section === 'websites' || section === 'overview'" type="primary" @click="openForm()">＋ 添加网站</el-button><el-button v-if="section === 'detail'" @click="router.push('/websites')">返回网站列表</el-button></div>
   <el-alert v-if="error" :title="error" type="error" show-icon @close="error = ''" /><el-alert v-if="feedback" :title="feedback" type="success" @close="feedback = ''" />
   <template v-if="section === 'overview'"><div class="stats"><el-card v-for="item in [{ label: '全部网站', value: overview.total, cls: '' }, { label: '访问正常', value: overview.normal, cls: 'green' }, { label: '无法访问', value: overview.down, cls: 'red' }, { label: '等待检查 / 已暂停', value: `${overview.pending} / ${overview.paused}`, cls: '' }]" :key="item.label" shadow="never"><span class="muted">{{ item.label }}</span><strong :class="item.cls">{{ item.value }}</strong></el-card></div><el-alert v-if="!overview.scheduler_healthy" title="检测调度暂未就绪，请检查主服务器监控服务" type="warning" :closable="false" /><el-card shadow="never"><div class="card-heading"><h3>近期故障</h3><router-link to="/incidents">查看全部 →</router-link></div><el-table :data="incidents.slice(0, 8)" empty-text="暂无故障记录。添加网站后即可开始检测。"><el-table-column prop="name" label="网站" min-width="150" /><el-table-column label="问题" min-width="120"><template #default="{ row }">{{ kindName(row.kind) }}</template></el-table-column><el-table-column label="发生时间（北京时间）" min-width="190"><template #default="{ row }">{{ beijingTime(row.started) }}</template></el-table-column><el-table-column label="状态"><template #default="{ row }"><el-tag :type="row.ended ? 'success' : 'danger'">{{ row.ended ? '已结束' : '处理中' }}</el-tag></template></el-table-column></el-table></el-card><p class="small muted">连续 3 次失败触发故障，连续 2 次成功触发恢复。返回 200 的错误页面可通过关键词进一步识别。</p></template>
   <template v-if="section === 'websites'"><el-card shadow="never"><div class="filters"><el-input v-model="filter.q" placeholder="搜索网站名称或域名" clearable @keyup.enter="search" /><el-select v-model="filter.node" placeholder="全部服务器" clearable @change="search"><el-option v-for="node in session?.nodes || []" :key="node.id" :label="node.name" :value="node.id" /></el-select><el-select v-model="filter.status" placeholder="全部状态" clearable @change="search"><el-option v-for="(label, key) in { normal: '正常', down: '无法访问', pending: '等待检查', paused: '已暂停' }" :key="key" :label="label" :value="key" /></el-select><el-button @click="search">查询</el-button></div><el-table :data="sites" empty-text="还没有网站，请点击“添加网站”。"><el-table-column label="网站 / 首页地址" min-width="230"><template #default="{ row }"><router-link :to="`/websites/${row.id}`" class="site-name">{{ row.name }}</router-link><UrlLink :url="row.url" /></template></el-table-column><el-table-column label="状态" min-width="110"><template #default="{ row }"><el-tag :type="row.paused ? 'info' : row.state.status === 'normal' ? 'success' : row.state.status === 'down' ? 'danger' : 'warning'">{{ stateLabel(row) }}</el-tag></template></el-table-column><el-table-column label="响应时间" min-width="105"><template #default="{ row }">{{ row.state.last.time ? Math.round(row.state.last.latency * 1000) + ' ms' : '—' }}</template></el-table-column><el-table-column label="证书有效期" min-width="160"><template #default="{ row }"><span :class="{ red: row.state.last.cert_expires && row.state.last.cert_expires <= Date.now() / 1000 + 7 * 86400 }">{{ certificateLabel(row) }}</span></template></el-table-column><el-table-column label="最近检查（北京时间）" min-width="190"><template #default="{ row }">{{ beijingTime(row.state.last.time) }}</template></el-table-column><el-table-column label="关联服务器" min-width="120"><template #default="{ row }">{{ nodeName(row.node) }}</template></el-table-column><el-table-column label="操作" width="240"><template #default="{ row }"><el-button link type="primary" @click="openForm(row)">编辑</el-button><el-button link type="primary" :disabled="row.paused" @click="check(row)">检查</el-button><el-button link @click="toggle(row)">{{ row.paused ? '恢复' : '暂停' }}</el-button><el-button link type="danger" @click="deleteId = row.id">删除</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="filter.page" v-model:page-size="filter.page_size" :page-sizes="[20, 50, 100]" :total="total" layout="total, sizes, prev, pager, next" @change="refresh" /></el-card></template>
   <template v-if="section === 'detail' && detail"><el-card shadow="never"><div class="card-heading"><div><h2>{{ detail.name }}</h2><a :href="detail.url" target="_blank" rel="noopener noreferrer">{{ detail.url }}</a></div><el-tag :type="detail.paused ? 'info' : detail.state.status === 'down' ? 'danger' : detail.state.status === 'pending' ? 'warning' : 'success'">{{ stateLabel(detail) }}</el-tag></div><div class="detail-grid"><div><span>关联服务器</span><strong>{{ nodeName(detail.node) }}</strong></div><div><span>最近检查（北京时间）</span><strong>{{ beijingTime(detail.state.last.time) }}</strong></div><div><span>HTTP 状态 / 耗时</span><strong>{{ detail.state.last.http_status || '—' }} / {{ Math.round(detail.state.last.latency * 1000) }} ms</strong></div><div><span>证书到期（北京时间）</span><strong>{{ detail.state.last.cert_expires ? beijingTime(detail.state.last.cert_expires) : '暂无证书信息' }}</strong></div><div><span>证书检测域名</span><strong>{{ detail.state.last.cert_host || '尚未取得' }}</strong></div><div><span>证书有效期</span><strong>{{ certificateLabel(detail) }}</strong></div><div><span>最近证书检查（北京时间）</span><strong>{{ beijingTime(detail.state.last.cert_checked || 0) }}</strong></div><div><span>检查成功率</span><strong>{{ detail.state.checks ? (100 * detail.state.passed / detail.state.checks).toFixed(1) : '0' }}%</strong></div><div><span>页面关键词</span><strong>{{ detail.keyword || '未设置' }}</strong></div></div><el-alert v-if="detail.state.last.reason" :title="detail.state.last.reason" type="warning" :closable="false" /><div class="actions"><el-button type="primary" :disabled="detail.paused" @click="check(detail)">立即检查</el-button><el-button @click="openForm(detail)">编辑设置</el-button><el-button @click="toggle(detail)">{{ detail.paused ? '恢复检测' : '暂停检测' }}</el-button></div></el-card></template>
   <el-card v-if="section === 'incidents' || section === 'detail'" shadow="never"><h3>故障历史</h3><el-table :data="incidents" empty-text="暂无故障历史"><el-table-column prop="name" label="网站" min-width="160" /><el-table-column label="问题" min-width="120"><template #default="{ row }">{{ kindName(row.kind) }}</template></el-table-column><el-table-column prop="reason" label="原因" min-width="230" /><el-table-column label="发生时间（北京时间）" min-width="190"><template #default="{ row }">{{ beijingTime(row.started) }}</template></el-table-column><el-table-column label="结束时间（北京时间）" min-width="190"><template #default="{ row }">{{ row.ended ? beijingTime(row.ended) : '仍在持续' }}</template></el-table-column></el-table><el-pagination v-model:current-page="historyPage" :page-size="20" :total="historyTotal" layout="total, prev, pager, next" @change="refresh" /></el-card>
   <Backups v-if="section === 'backups'" />
   <footer>智慧网站监控 · 首页检查由主服务器执行 · 故障历史保留 30 天</footer>
  </main></div>
  <PasswordDialog v-model="passwordDialog" @changed="passwordChanged" />
  <el-dialog v-model="dialog" :title="editId ? '编辑网站' : '添加网站'" width="min(560px, 94vw)" :close-on-click-modal="false"><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-form label-position="top" @submit.prevent="save"><el-form-item label="网站名称"><el-input v-model="form.name" maxlength="100" placeholder="例如：公司官网" /></el-form-item><el-form-item label="首页地址（公网 HTTP / HTTPS）"><el-input v-model="form.url" placeholder="https://www.example.com/" /></el-form-item><el-form-item label="关联服务器（可选，仅用于分类）"><el-select v-model="form.node" clearable placeholder="不关联服务器"><el-option v-for="node in session?.nodes || []" :key="node.id" :label="node.name" :value="node.id" /></el-select></el-form-item><el-form-item label="首页必须包含的关键词（可选）"><el-input v-model="form.keyword" maxlength="200" placeholder="例如：公司名称，帮助识别返回 200 的错误页面" /></el-form-item><el-form-item label="响应缓慢告警"><el-switch v-model="form.slow_alert" /><span class="small muted switch-note">超过 3 秒并持续 5 分钟时提醒</span></el-form-item><el-form-item label="暂停检测"><el-switch v-model="form.paused" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="busy" @click="save">保存网站</el-button></template></el-dialog>
  <el-dialog :model-value="deleteId !== 0" title="删除网站" width="min(440px, 94vw)" @close="deleteId = 0"><p>删除后停止检查，已有故障历史继续保留。确认删除此网站？</p><template #footer><el-button @click="deleteId = 0">取消</el-button><el-button type="danger" :loading="busy" @click="remove">确认删除</el-button></template></el-dialog>
 </div>
 </el-config-provider>
</template>
